#!/usr/bin/env node
/**
 * Generate `Sources/NexusKit/Generated/Themes.swift` from `@nexuscode/theme`.
 *
 * The terminal already ships a complete design system: ~101 semantic tokens
 * across 17 themes, every one of which every theme must fill. Hand-copying that
 * into Swift would guarantee drift and would be ~1,700 literals of tedium. This
 * imports the BUILT package and emits the values it actually resolves, so the
 * app and the TUI render the same palette by construction — pick "Nexus Noir"
 * in either and you get the same colours.
 *
 * Run from the repo root (needs `npm run build --workspace=@nexuscode/theme`):
 *   node apps/nexus-mac/tools/generate-themes.mjs
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const outPath = resolve(here, "../Sources/NexusKit/Generated/Themes.swift");

const theme = await import(resolve(repoRoot, "packages/theme/dist/index.js"));
const { BUILTIN_THEME_LIST, BUILTIN_THEMES, TOKEN_IDS, DEFAULT_THEME_ID } = theme;

if (!Array.isArray(BUILTIN_THEME_LIST) || BUILTIN_THEME_LIST.length === 0) {
  throw new Error("no themes found — run `npm run build --workspace=@nexuscode/theme` first");
}

/** `surface.base` -> `surfaceBase`, so tokens are Swift properties. */
function swiftName(token) {
  return token
    .split(".")
    .map((part, index) =>
      index === 0
        ? part
        : part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join("")
    .replace(/[^A-Za-z0-9]/g, "");
}

/** Resolve a token to a `#rrggbb` literal, following `@primitive` refs. */
function resolveColor(themeValue, primitives, token) {
  let value = themeValue;
  const seen = new Set();
  while (typeof value === "string" && value.startsWith("@")) {
    const key = value.slice(1);
    if (seen.has(key)) throw new Error(`cyclic primitive @${key} for ${token}`);
    seen.add(key);
    value = primitives?.[key];
  }
  if (typeof value !== "string" || !/^#[0-9a-f]{3,8}$/i.test(value)) {
    return null;
  }
  return value;
}

const tokens = [...TOKEN_IDS];
const seenNames = new Map();
for (const token of tokens) {
  const name = swiftName(token);
  if (seenNames.has(name)) {
    throw new Error(`token name collision: ${token} and ${seenNames.get(name)} both -> ${name}`);
  }
  seenNames.set(name, token);
}

const lines = [];
lines.push("// GENERATED by tools/generate-themes.mjs — DO NOT EDIT BY HAND.");
lines.push("//");
lines.push("// Source of truth: packages/theme (the same palettes the TUI renders).");
lines.push("// Regenerate: node apps/nexus-mac/tools/generate-themes.mjs");
lines.push("");
lines.push("import SwiftUI");
lines.push("");
lines.push("/// Every semantic token a theme defines. No view names a raw colour;");
lines.push("/// each visual role is a token here, exactly as in the terminal theme layer.");
lines.push("/// Every semantic token a theme defines. `var`, not `let`: a `ThemeSeed`'s");
lines.push("/// `overrides` closure mutates a finished token set in place (see");
lines.push("/// `ThemeDerivation.swift`), which is the per-theme escape hatch from the");
lines.push("/// derivation. Still a value type, so nothing is shared.");
lines.push("public struct ThemeTokens: Sendable, Hashable {");
for (const token of tokens) {
  lines.push(`    public var ${swiftName(token)}: String`);
}
lines.push("}");
lines.push("");
lines.push("public struct NexusTheme: Sendable, Hashable, Identifiable {");
lines.push("    public let id: String");
lines.push("    public let name: String");
lines.push("    public let isDark: Bool");
lines.push("    public let tokens: ThemeTokens");
lines.push("");
lines.push("    /// Sibling theme for OS light/dark auto-pairing, when the theme declares one.");
lines.push("    public let pairId: String?");
lines.push("}");
lines.push("");

const emitted = [];
const skipped = [];

for (const entry of BUILTIN_THEME_LIST) {
  const id = entry.meta.id;
  const full = BUILTIN_THEMES[id] ?? entry;
  const primitives = full.primitives ?? {};
  const values = [];
  let incomplete = null;

  for (const token of tokens) {
    const color = resolveColor(full.tokens?.[token], primitives, token);
    if (!color) {
      incomplete = token;
      break;
    }
    values.push(`        ${swiftName(token)}: "${color}"`);
  }

  if (incomplete) {
    // A theme using `extends` has a partial token map; emitting it half-filled
    // would silently render wrong colours, so it is skipped loudly instead.
    skipped.push(`${id} (missing ${incomplete})`);
    continue;
  }

  const varName = id.replace(/[^a-z0-9]+(.)/gi, (_, c) => c.toUpperCase());
  emitted.push({ id, varName });
  lines.push(`public extension NexusTheme {`);
  lines.push(`    static let ${varName} = NexusTheme(`);
  lines.push(`        id: ${JSON.stringify(id)},`);
  lines.push(`        name: ${JSON.stringify(entry.meta.name)},`);
  lines.push(`        isDark: ${entry.meta.mode === "dark"},`);
  lines.push(`        tokens: ThemeTokens(`);
  lines.push(values.join(",\n"));
  lines.push(`        ),`);
  lines.push(`        pairId: ${entry.meta.pairId ? JSON.stringify(entry.meta.pairId) : "nil"}`);
  lines.push(`    )`);
  lines.push(`}`);
  lines.push("");
}

lines.push("public extension NexusTheme {");
lines.push("    /// Every built-in theme, in the same order the terminal lists them.");
lines.push("    static let all: [NexusTheme] = [");
for (const { varName } of emitted) lines.push(`        .${varName},`);
lines.push("    ]");
lines.push("");
lines.push(`    static let defaultThemeId = ${JSON.stringify(DEFAULT_THEME_ID)}`);
lines.push("");
lines.push("    static func named(_ id: String) -> NexusTheme? {");
lines.push("        all.first { $0.id == id }");
lines.push("    }");
lines.push("}");
lines.push("");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n"));

console.log(`generated ${emitted.length} themes x ${tokens.length} tokens -> ${outPath}`);
if (skipped.length > 0) {
  console.log(`skipped (incomplete token maps): ${skipped.join(", ")}`);
}
