/** Glacier — arctic deep-focus dark theme (design spec §5.4). */

import { defineTheme } from "./define.js";

export const glacier = defineTheme({
  meta: {
    id: "glacier",
    name: "Glacier",
    author: "NexusCode",
    version: "1.0.0",
    mode: "dark",
    license: "MIT",
    minContrast: "AA",
  },
  tokens: {
    "surface.sunken": "#080D14",
    "surface.base": "#0E1620",
    "surface.raised": "#18222E",
    "surface.overlay": "#1E2A38",
    "surface.inset": "#131D28",

    "text.primary": "#DCE7F0",
    "text.secondary": "#9CB0C4",
    "text.muted": "#788D9E",
    "text.inverse": "#0E1620",
    "text.link": "#6FB4E8",

    "chrome.border": "#2A3947",
    "chrome.border.subtle": "#1F2C38",
    "chrome.border.strong": "#4A5D6E",
    "chrome.borderFocus": "#5BD6E8",
    "chrome.title": "#DCE7F0",
    "chrome.divider": "#1F2C38",

    "accent.default": "#5BD6E8",
    "accent.emphasis": "#8AE6F2",
    "accent.muted": "#3A97A5",
    "accent.fg": "#0E1620",

    "success.fg": "#57C8A6",
    "success.bg": "#0C241E",
    "success.border": "#3A9880",
    "warning.fg": "#E3C36A",
    "warning.bg": "#241F0F",
    "warning.border": "#B39A4A",
    "error.fg": "#F17A8A",
    "error.bg": "#2A0F14",
    "error.border": "#C55565",
    "info.fg": "#6FB4E8",
    "info.bg": "#0C2033",
    "info.border": "#4A8BC0",

    "stream.cursor": "#7DE8F5",
    "stream.thinking": "#788D9E",
    "stream.text": "#DCE7F0",

    "diff.added.fg": "#57C8A6",
    "diff.added.bg": "#0C241E",
    "diff.removed.fg": "#F17A8A",
    "diff.removed.bg": "#2A0F14",
    "diff.context": "#788D9E",
    "diff.gutter": "#4A5D6E",

    "syntax.keyword": "#F17A8A",
    "syntax.function": "#A9A0F0",
    "syntax.type": "#7CB4F0",
    "syntax.string": "#57C8A6",
    "syntax.number": "#E3C36A",
    "syntax.comment": "#788D9E",
    "syntax.operator": "#9CB0C4",
    "syntax.variable": "#DCE7F0",
    "syntax.constant": "#7CB4F0",
    "syntax.tag": "#57C8A6",
    "syntax.attribute": "#E3C36A",
    "syntax.invalid": "#F17A8A",

    "provider.anthropic": "#E39A78",
    "provider.openai": "#4FCFB0",
    "provider.google": "#7CB4F0",
    "provider.xai": "#C7D4E0",
    "provider.ollama": "#A9A0F0",
    "provider.mistral": "#F0925A",
    "provider.deepseek": "#6E8CF0",
    "provider.custom": "#E88AC8",

    "cost.ok": "#57C8A6",
    "cost.warn": "#E3C36A",
    "cost.crit": "#F17A8A",

    "selection.bg": "#1E2A38",
    "selection.fg": "#DCE7F0",
    "focus.ring": "#5BD6E8",
    "badge.bg": "#18222E",
    "badge.fg": "#DCE7F0",
    "scrollbar.track": "#18222E",
    "scrollbar.thumb": "#4A5D6E",
    "spinner": "#5BD6E8",
    "link.visited": "#A9A0F0",
    "overlay.scrim": "#080D14",
  },
});
