/** Paper Nexus — OS-auto light sibling of Nexus Noir (design spec §5.2). */

import { defineTheme } from "./define.js";

export const paperNexus = defineTheme({
  meta: {
    id: "paper-nexus",
    name: "Paper Nexus",
    author: "NexusCode",
    version: "1.0.0",
    mode: "light",
    followsOs: true,
    pairId: "nexus-noir",
    license: "MIT",
    minContrast: "AA",
  },
  tokens: {
    "surface.sunken": "#EFE9DD",
    "surface.base": "#FBF7EF",
    "surface.raised": "#FFFFFF",
    "surface.overlay": "#FFFFFF",
    "surface.inset": "#F0EBE0",

    "text.primary": "#1C2024",
    "text.secondary": "#4A5158",
    "text.muted": "#696F77",
    "text.inverse": "#FBF7EF",
    "text.link": "#0A5FB4",

    "chrome.border": "#D8D0C0",
    "chrome.border.subtle": "#E5DECF",
    "chrome.border.strong": "#B5AC98",
    "chrome.borderFocus": "#0E7C86",
    "chrome.title": "#1C2024",
    "chrome.divider": "#E5DECF",

    "accent.default": "#0E7C86",
    "accent.emphasis": "#0A5C64",
    "accent.muted": "#8FBFC4",
    "accent.fg": "#FBF7EF",

    "success.fg": "#1A7F37",
    "success.bg": "#E7F3E4",
    "success.border": "#2DA44E",
    "warning.fg": "#8A6100",
    "warning.bg": "#F5E9C8",
    "warning.border": "#BF8700",
    "error.fg": "#C02A2A",
    "error.bg": "#FBE7E4",
    "error.border": "#CF222E",
    "info.fg": "#0A5FB4",
    "info.bg": "#DDEBFB",
    "info.border": "#0969DA",

    "stream.cursor": "#0E7C86",
    "stream.thinking": "#696F77",
    "stream.text": "#1C2024",

    "diff.added.fg": "#136A2E",
    "diff.added.bg": "#E7F3E4",
    "diff.removed.fg": "#B01E1E",
    "diff.removed.bg": "#FBE7E4",
    "diff.context": "#696F77",
    "diff.gutter": "#B5AC98",

    "syntax.keyword": "#CF222E",
    "syntax.function": "#8250DF",
    "syntax.type": "#0550AE",
    "syntax.string": "#116329",
    "syntax.number": "#953800",
    "syntax.comment": "#696F77",
    "syntax.operator": "#4A5158",
    "syntax.variable": "#1C2024",
    "syntax.constant": "#0550AE",
    "syntax.tag": "#116329",
    "syntax.attribute": "#953800",
    "syntax.invalid": "#CF222E",

    "provider.anthropic": "#B24B28",
    "provider.openai": "#0B6B54",
    "provider.google": "#1A5FC4",
    "provider.xai": "#2E353B",
    "provider.ollama": "#6A45C2",
    "provider.mistral": "#B24E00",
    "provider.deepseek": "#2B4ACB",
    "provider.custom": "#A83E8C",

    "cost.ok": "#1A7F37",
    "cost.warn": "#8A6100",
    "cost.crit": "#C02A2A",

    "selection.bg": "#D6E4F0",
    "selection.fg": "#1C2024",
    "focus.ring": "#0E7C86",
    "badge.bg": "#EDE7DA",
    "badge.fg": "#1C2024",
    "scrollbar.track": "#EDE7DA",
    "scrollbar.thumb": "#B5AC98",
    "spinner": "#0E7C86",
    "link.visited": "#6639BA",
    "overlay.scrim": "#1C2024",
  },
});
