/** Retro Amber — Warm retro terminal — dark brown-olive surfaces with amber, orange, yellow, green and aqua. */

import { defineTheme } from "./define.js";

export const retroAmber = defineTheme({
  meta: {
    id: "retro-amber",
    name: "Retro Amber",
    author: "NexusCode",
    version: "1.0.0",
    mode: "dark",
    license: "MIT",
    minContrast: "AA",
  },
  tokens: {
    "surface.sunken": "#1A1712",
    "surface.base": "#282520",
    "surface.raised": "#35302A",
    "surface.overlay": "#3E3830",
    "surface.inset": "#211E19",
    "text.primary": "#F2E5C8",
    "text.secondary": "#D4C4A0",
    "text.muted": "#A99C7F",
    "text.inverse": "#282520",
    "text.link": "#83C07D",
    "chrome.border": "#4A4437",
    "chrome.border.subtle": "#3C372D",
    "chrome.border.strong": "#6B6350",
    "chrome.borderFocus": "#FE9E3F",
    "chrome.title": "#F2E5C8",
    "chrome.divider": "#3C372D",
    "accent.default": "#FE9E3F",
    "accent.emphasis": "#FFBE70",
    "accent.muted": "#C46A1E",
    "accent.fg": "#282520",
    "success.fg": "#B8BB26",
    "success.bg": "#232A10",
    "success.border": "#79880F",
    "warning.fg": "#FABD2F",
    "warning.bg": "#2E2610",
    "warning.border": "#C79212",
    "error.fg": "#FB5A48",
    "error.bg": "#301410",
    "error.border": "#CC3226",
    "info.fg": "#83C07D",
    "info.bg": "#14260F",
    "info.border": "#4E8F4A",
    "stream.cursor": "#FABD2F",
    "stream.thinking": "#A99C7F",
    "stream.text": "#F2E5C8",
    "diff.added.fg": "#B8BB26",
    "diff.added.bg": "#232A10",
    "diff.removed.fg": "#FB5A48",
    "diff.removed.bg": "#301410",
    "diff.context": "#A99C7F",
    "diff.gutter": "#6B6350",
    "syntax.keyword": "#FB5A48",
    "syntax.function": "#B8BB26",
    "syntax.type": "#FABD2F",
    "syntax.string": "#83C07D",
    "syntax.number": "#D3869B",
    "syntax.comment": "#A99C7F",
    "syntax.operator": "#D4C4A0",
    "syntax.variable": "#F2E5C8",
    "syntax.constant": "#D3869B",
    "syntax.tag": "#FB5A48",
    "syntax.attribute": "#B8BB26",
    "syntax.invalid": "#FB5A48",
    "provider.anthropic": "#FE9E3F",
    "provider.openai": "#B8BB26",
    "provider.google": "#83C07D",
    "provider.xai": "#F2E5C8",
    "provider.ollama": "#D3869B",
    "provider.mistral": "#FB5A48",
    "provider.deepseek": "#83A598",
    "provider.custom": "#FABD2F",
    "cost.ok": "#B8BB26",
    "cost.warn": "#FABD2F",
    "cost.crit": "#FB5A48",
    "selection.bg": "#3E3830",
    "selection.fg": "#F2E5C8",
    "focus.ring": "#FE9E3F",
    "badge.bg": "#35302A",
    "badge.fg": "#F2E5C8",
    "scrollbar.track": "#35302A",
    "scrollbar.thumb": "#6B6350",
    "spinner": "#FE9E3F",
    "link.visited": "#D3869B",
    "overlay.scrim": "#1A1712",
  },
});
