/** Synthwave Grid — demo-flair dark theme, still AA (design spec §5.6). */

import { defineTheme } from "./define.js";

export const synthwaveGrid = defineTheme({
  meta: {
    id: "synthwave-grid",
    name: "Synthwave Grid",
    author: "NexusCode",
    version: "1.0.0",
    mode: "dark",
    license: "MIT",
    minContrast: "AA",
  },
  tokens: {
    "surface.sunken": "#0E0820",
    "surface.base": "#160E2E",
    "surface.raised": "#20153E",
    "surface.overlay": "#291C4A",
    "surface.inset": "#1B1236",

    "text.primary": "#F0E9FF",
    "text.secondary": "#C0AEEE",
    "text.muted": "#8A7BC0",
    "text.inverse": "#160E2E",
    "text.link": "#6BB6FF",

    "chrome.border": "#3A2C5E",
    "chrome.border.subtle": "#2A1E48",
    "chrome.border.strong": "#5A4A8E",
    "chrome.borderFocus": "#FF4FD8",
    "chrome.title": "#F0E9FF",
    "chrome.divider": "#2A1E48",

    "accent.default": "#FF4FD8",
    "accent.emphasis": "#FF85E6",
    "accent.muted": "#B03698",
    "accent.fg": "#160E2E",

    "success.fg": "#5CF08A",
    "success.bg": "#0C2416",
    "success.border": "#3AB064",
    "warning.fg": "#FFD24A",
    "warning.bg": "#2A2410",
    "warning.border": "#C7A430",
    "error.fg": "#FF5C7A",
    "error.bg": "#2A0F18",
    "error.border": "#C7455E",
    "info.fg": "#6BB6FF",
    "info.bg": "#0C1E33",
    "info.border": "#4A8BC7",

    "stream.cursor": "#4EE6F5",
    "stream.thinking": "#8A7BC0",
    "stream.text": "#F0E9FF",

    "diff.added.fg": "#5CF08A",
    "diff.added.bg": "#0C2416",
    "diff.removed.fg": "#FF5C7A",
    "diff.removed.bg": "#2A0F18",
    "diff.context": "#8A7BC0",
    "diff.gutter": "#5A4A8E",

    "syntax.keyword": "#FF4FD8",
    "syntax.function": "#C77DFF",
    "syntax.type": "#6BB6FF",
    "syntax.string": "#5CF08A",
    "syntax.number": "#FFD24A",
    "syntax.comment": "#8A7BC0",
    "syntax.operator": "#C0AEEE",
    "syntax.variable": "#F0E9FF",
    "syntax.constant": "#4EE6F5",
    "syntax.tag": "#5CF08A",
    "syntax.attribute": "#FFD24A",
    "syntax.invalid": "#FF5C7A",

    "provider.anthropic": "#FF9E6E",
    "provider.openai": "#4EF0C4",
    "provider.google": "#7AA8FF",
    "provider.xai": "#D8CFF0",
    "provider.ollama": "#C77DFF",
    "provider.mistral": "#FF7AA0",
    "provider.deepseek": "#6B8CFF",
    "provider.custom": "#FF6BE0",

    "cost.ok": "#5CF08A",
    "cost.warn": "#FFD24A",
    "cost.crit": "#FF5C7A",

    "selection.bg": "#291C4A",
    "selection.fg": "#F0E9FF",
    "focus.ring": "#FF4FD8",
    "badge.bg": "#20153E",
    "badge.fg": "#F0E9FF",
    "scrollbar.track": "#20153E",
    "scrollbar.thumb": "#5A4A8E",
    "spinner": "#4EE6F5",
    "link.visited": "#C77DFF",
    "overlay.scrim": "#0E0820",
  },
});
